name: Github Actions with IAM Role

on: [push]

permissions:
  contents: read
  id-token: write

jobs:
  AssumeRole:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ['eu-west-1', 'us-east-1']  # Define regions in the matrix
        iam-role: ['BONP_BAMBOO']        # IAM role secrets

    steps:
    - name: Clone Repository
      uses: actions/checkout@v4

    - name: Set IAM Role from Secrets
      run: echo "IAM_ROLE=${{ secrets[matrix.iam-role] }}" >> $GITHUB_ENV

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.IAM_ROLE }}
        role-session-name: github-actions-federation
        aws-region: ${{ matrix.region }}

    - name: Display Role and Region
      run: |
        echo "Running in AWS Region: ${{ matrix.region }}"
        echo "Assumed IAM Role: ${{ env.IAM_ROLE }}"

    - name: List Lambda Functions in Region
      run: |
        echo "Listing Lambda functions in region ${{ matrix.region }}"
        output_file="lambda_functions_${{ matrix.region }}_${{ matrix.iam-role }}.md"
        
        # Generate Markdown output
        echo "# Lambda Functions in ${{ matrix.region }} (Role: ${{ matrix.iam-role }})" > $output_file
        echo "" >> $output_file
        aws lambda list-functions --region ${{ matrix.region }} --query "Functions[*].[FunctionName, Runtime, LastModified, MemorySize]" --output table >> $output_file
        
        echo "Lambda functions for region ${{ matrix.region }} and role ${{ matrix.iam-role }} saved to $output_file"

    - name: Upload Lambda Functions Markdown Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: lambda-functions-md-${{ matrix.region }}-${{ matrix.iam-role }}
        path: lambda_functions_${{ matrix.region }}_${{ matrix.iam-role }}.md
