name: Github actions with IAM Role
on: [push]

env:
  AWS_REGION: ${{ secrets.REGION }}
  IAM_ROLE: ${{ secrets.IAM_ROLE }}

permissions:
  contents: read
  id-token: write

jobs:
  AssumeRole:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.IAM_ROLE }}
        role-session-name: github-actions-federation
        aws-region: ${{ env.AWS_REGION }}

    - name: List Buckets
      run: aws s3 ls
